// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CognitiveServices.Android {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesTexts {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesTexts() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CognitiveServices.Android.ResourcesTexts", typeof(ResourcesTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        internal static string MSCS {
            get {
                return ResourceManager.GetString("MSCS", resourceCulture);
            }
        }
        
        internal static string Analyzing {
            get {
                return ResourceManager.GetString("Analyzing", resourceCulture);
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        internal static string Glasses {
            get {
                return ResourceManager.GetString("Glasses", resourceCulture);
            }
        }
        
        internal static string Beard {
            get {
                return ResourceManager.GetString("Beard", resourceCulture);
            }
        }
        
        internal static string Moustache {
            get {
                return ResourceManager.GetString("Moustache", resourceCulture);
            }
        }
        
        internal static string Sideburns {
            get {
                return ResourceManager.GetString("Sideburns", resourceCulture);
            }
        }
        
        internal static string Smile {
            get {
                return ResourceManager.GetString("Smile", resourceCulture);
            }
        }
        
        internal static string Initializing {
            get {
                return ResourceManager.GetString("Initializing", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string AddFace {
            get {
                return ResourceManager.GetString("AddFace", resourceCulture);
            }
        }
        
        internal static string AddingFace {
            get {
                return ResourceManager.GetString("AddingFace", resourceCulture);
            }
        }
        
        internal static string FaceAdded {
            get {
                return ResourceManager.GetString("FaceAdded", resourceCulture);
            }
        }
        
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
    }
}
